on:
  push:
    branches:
      - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # install and lint
      - run: pip install -r layers/curiosity_pipeline/requirements.txt --user
      - run: python -m flake8 --select F401,F821,E302,E305,E501,F841,W291 --max-line-length 100
      - name: Test network connectivity
        run: |
          curl -v https://api.pinecone.io
          curl -v https://api.openai.com/v1
          curl -v "https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=4061&api_key=${{ secrets.NASA_API_KEY }}"
      - run: python -m pytest tests/unit -v
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}

      # sam build 
      - run: sam build --use-container
