on:
  push:
    branches:
      - develop
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # install and lint
      - name: Create env file
        run: |
          touch .env
          echo NASA_API_KEY=${{ secrets.NASA_API_KEY }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} >> .env
          echo S3_BUCKET=${{ vars.S3_BUCKET }} >> .env
          cat .env
      - run: pip install -r layers/curiosity_pipeline/requirements.txt --user
      - run: python -m flake8 --select F401,F821,E302,E305,E501,F841,W291 --max-line-length 100
      - run: python -m pytest tests/unit -v

      # sam build 
      - run: sam build --use-container
