on:
  push:
    branches:
      - release
jobs:
  build-deploy:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Clean up _temp directory
        run: rm -rf ${{ runner.temp }}

    # Add other steps here
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SAM validate
        run: sam validate
 